# -*- coding: utf-8 -*-
"""lvadsusr80_D.stuthi_lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ozh19YpQwR6USfOU3QbcaVzIv1Rg6dg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,accuracy_score
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
from sklearn.ensemble import IsolationForest

df=pd.read_csv('/content/social_network.csv')
df

df.isnull().sum()

df.isna().sum()

df.columns

df.info()

X=df[['user_id', 'account_creation_date', 'account_status', 'login_activity','posting_activity', 'social_connections', 'suspicious_activity']]

X.isna().sum()
X=X.dropna()

l=LabelEncoder()
df['account_creation_date']=l.fit_transform(df['account_creation_date'])
df['account_status']=l.fit_transform(df['account_status'])
X=df[['user_id', 'account_creation_date', 'account_status', 'login_activity','posting_activity', 'social_connections', 'suspicious_activity']]
s=StandardScaler()
Xs=s.fit_transform(X)
Model=IsolationForest()
Model.fit(Xs)
Anamoly=Model.predict(Xs)
df['anamoly']=Anamoly
df
a=df[Anamoly>0]
b=df[Anamoly<0]
plt.scatter(a['anamoly'],a['login_activity'],color='blue')
plt.sctter(b['anamoly'],a['login_activity'],color='black')
plt.show()